### ISSUE TITLE
Theano - deprecated functions 

### ISSUE THREAD

**Issue by MrtnMndt** [Rhoana/icon#1]
I just thought of notifying you that when trying to use your code with the latest theano version I stumbled into a bunch of issues.

  `from theano.tensor.signal import downsample` 
should entirely be replaced by 
  `from theano.tensor.signal import pool` 
as the former is no longer working.  

As a consequence 
`downsample.max_pool_2d(` 
should be replaced by 
`pool.pool_2d`  

Apart from this there is also several warnings e.g. _the 'ds' parameter is not going to exist anymore as it is going to be replaced by the parameter 'ws'._

**Comment by MrtnMndt** [comment]
I guess the project isn't being maintained. Closing the issue.

**Comment by fegonda** [comment]
Hi Martin,
Sorry I haven't seen your message. I'll look into the issue.

Felix
